addLetters('a', 'b', 'c') // should return 'f'
addLetters('a', 'b') // should return 'c'
addLetters('z') // should return 'z'
addLetters('z', 'a') // should return 'a'
addLetters('y', 'c', 'b') // should return 'd'
addLetters() // should return 'z'
